
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L) || defined(__QNXNTO__)

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[184] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   67,   67,    0,    0,    0,    0,   71,   70,
        8,    1,    8,    8,    8,    8,    8,   42,   38,   32,
       27,   12,   13,   42,   14,   42,   37,   15,   29,   28,
       30,   31,   34,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   10,   11,   41,   62,   63,   62,   62,
       66,   65,   55,   50,   51,   53,   54,   55,   68,   69,
       67,   67,   56,   57,   58,   59,   60,   46,   45,   70,
       43,   70,   44,   49,   47,    9,    0,    0,    0,    0,
        0,    0,   36,   37,   39,   40,   37,   34,   35,   34,

       35,   35,   35,   23,   16,   33,   35,   35,   24,   35,
       35,   26,   64,   61,   53,   54,    0,   68,   67,   67,
       59,   60,   48,   49,   49,   47,    0,    0,    0,    0,
        0,    0,   35,   35,   35,   35,   35,   35,   35,   35,
        0,    0,    0,    0,    0,    0,    0,   35,   35,   19,
       35,   21,   35,   18,   20,   52,    0,    0,    0,    0,
        0,    0,   25,   17,   16,   35,   35,   35,    0,    4,
        0,    5,    6,    3,   21,   35,   18,    0,    0,   22,
        7,    2,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    5,    8,    9,    5,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,    5,   20,
       21,   22,   23,    5,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       16,    5,   16,    5,   25,    5,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   35,   35,   36,   37,   38,
       39,   35,   35,   40,   41,   42,   43,   44,   35,   35,
       35,   35,   45,    5,   46,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    2,    1,    3,    2,    2,    2,    2,    2,    2,
        2,    2,    3,    2,    3,    4,    2,    4,    2,    2,
        2,    2,    5,    4,    6,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    2,    2
    } ;

static yyconst flex_int16_t yy_base[195] =
    {   0,
        0,    0,    0,    4,   47,  480,    1,    2,  483,  482,
       91,   92,   19,   25,   99,  107,  134,    0,  484,  488,
      488,  488,  475,  445,  439,  438,    1,  488,  488,  488,
        0,  488,  488,  460,  488,   18,  114,  488,  488,  488,
      488,  488,  177,    2,  178,  181,  184,  185,  199,  200,
      203,  204,  217,  488,  488,  488,  488,  488,  450,  412,
      488,  488,  488,  488,  488,  222,  230,  389,   94,  488,
       95,  412,  488,  488,  488,  245,  246,  488,  488,    0,
      488,  378,  488,  261,    0,  488,  369,  316,  328,  310,
      322,  312,    0,  262,  488,  488,  268,  269,   74,  284,

       85,  188,  202,   87,  223,  208,  251,  257,  261,  277,
      267,  271,  488,  488,  308,  309,  302,  313,  326,  329,
      325,  331,    0,  332,  344,    0,  277,  288,  265,  254,
      240,  226,  324,  286,  331,  303,  337,  333,  335,  348,
      238,  223,  212,  214,  197,  167,  171,  346,  345,  334,
      347,  356,  365,  358,  359,  488,  181,  146,  161,  143,
      142,   89,  366,  368,  369,  372,  376,  378,   84,  488,
       58,  488,  488,  488,  379,  386,  387,   10,    6,  388,
      488,  488,  488,  428,  434,  440,  446,  452,  458,    5,
      462,  467,  470,  473

    } ;

static yyconst flex_int16_t yy_def[195] =
    {   0,
      184,  184,  185,  185,  183,    5,  186,  186,  187,  187,
      188,  188,  189,  189,  184,  184,  183,   17,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      190,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      192,  192,  183,  183,  183,  183,  183,  183,  183,  193,
      183,  183,  183,  183,  194,  183,  183,  183,  183,  183,
      183,  183,  190,  183,  183,  183,  183,  183,   53,  191,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,  183,  183,  183,  183,  183,  183,  192,  192,
      183,  183,  193,  183,  183,  194,  183,  183,  183,  183,
      183,  183,   53,   53,   53,   53,   53,   53,   53,   53,
      183,  183,  183,  183,  183,  183,  183,   53,   53,   53,
       53,   53,   53,   53,   53,  183,  183,  183,  183,  183,
      183,  183,   53,   53,   53,   53,   53,   53,  183,  183,
      183,  183,  183,  183,   53,   53,   53,  183,  183,   53,
      183,  183,    0,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183

    } ;

static yyconst flex_int16_t yy_nxt[535] =
    {   0,
      183,  183,   22,   58,   58,  183,   22,   23,   93,  183,
      183,   23,   59,   59,  183,  183,  183,   60,   60,   20,
       69,   70,   71,  183,   71,   20,   69,   70,   71,   95,
       71,   90,   24,  183,   96,   94,   24,   91,   92,   25,
       26,  182,   27,   25,   26,  181,   27,   28,   28,   29,
       28,   28,   28,   28,   30,   31,   32,   33,   28,   34,
       35,   34,   28,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   44,   44,   44,   44,
       49,   44,   44,   44,   44,   50,   51,   52,   53,   44,
       44,   54,   55,   20,   20,  118,  118,  118,  119,  118,

      119,  179,   73,   64,   64,   65,   65,   99,   66,   66,
       73,   74,   99,   75,   67,   67,   76,   97,   99,   74,
       99,   75,   77,  133,   76,   99,   97,  178,   97,  174,
       77,   97,   68,   68,   20,   20,   78,   79,   20,   20,
       20,   20,   80,   20,   81,   20,   82,   83,   82,   20,
       82,   84,   20,   20,   20,   20,   20,   85,   20,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   20,   20,
       98,  183,  173,  172,  183,  171,  170,  183,  183,   98,
      183,   98,  183,  183,  100,  183,  183,  183,  183,  183,

      100,  100,  183,  183,  101,  169,  183,  183,  162,  161,
      102,  183,  183,  183,  183,  183,  183,  183,  183,  134,
      183,   99,  103,  104,  160,  115,   99,  105,  107,  183,
      135,  183,  108,  116,  115,   99,  115,  106,  109,  115,
       99,   99,  116,  159,  116,  110,   99,  116,  121,  122,
      111,  158,  136,  116,  116,  112,   99,  121,  122,  121,
      122,   99,  121,  122,  125,   97,  157,  156,  147,  122,
      122,   97,   98,  125,   97,  125,   97,  146,  125,   97,
       97,   98,   97,   98,   99,   97,   98,   98,  137,   99,
       99,  145,   98,   98,   99,   99,   98,  138,   98,   99,

       99,  100,  139,  140,   99,   99,  144,  100,  100,   99,
       99,  115,  116,  143,  118,   99,  118,  142,  118,  149,
      115,  116,  115,  116,   99,  115,  116,  118,  121,  119,
      183,  119,  116,  116,  122,  125,   99,  121,  141,  121,
      151,   99,  121,  122,  125,  122,  125,  125,  122,  125,
      132,  131,  130,  129,  122,  122,  125,   99,  125,  128,
      150,  125,   99,  148,   99,  152,   99,   99,   99,   99,
       99,   99,   99,   99,  153,   99,  154,  155,   99,   99,
       99,   99,  164,   99,   99,   99,   99,  163,  165,   99,
      167,   99,   99,  127,  166,  124,   99,   99,   99,   99,

      168,   99,   99,   99,   99,   99,   99,   99,  175,   99,
       99,   99,   99,  183,   99,  176,   99,   99,  177,   99,
       99,   99,  117,  114,   99,   99,   99,  180,   20,   20,
       20,   20,   20,   20,   21,   21,   21,   21,   21,   21,
       57,   57,   57,   57,   57,   57,   61,   61,   61,   61,
       61,   61,   63,   63,   63,   63,   63,   63,   72,   72,
       72,   72,   72,   72,   99,   99,  113,   99,  120,  120,
      120,  120,  120,  123,  123,  123,  126,   94,  126,   89,
       88,   87,   86,  183,   62,   62,   56,   19,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183
    } ;

static yyconst flex_int16_t yy_chk[535] =
    {   0,
        0,    0,    3,    7,    8,   44,    4,    3,  190,    0,
        0,    4,    7,    8,   44,    0,   44,    7,    8,   13,
       13,   13,   13,    0,   13,   14,   14,   14,   14,   36,
       14,   27,    3,    0,   36,   36,    4,   27,   27,    3,
        3,  179,    3,    4,    4,  178,    4,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,   11,   12,   69,   71,   69,   71,   69,

       71,  171,   15,   11,   12,   11,   12,   99,   11,   12,
       16,   15,   99,   15,   11,   12,   15,   37,  101,   16,
      104,   16,   15,  101,   16,  104,   37,  169,   37,  162,
       16,   37,   11,   12,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       43,   45,  161,  160,   46,  159,  158,   47,   48,   43,
       45,   43,   45,   46,   43,   46,   47,   48,   47,   48,

       43,   43,   49,   50,   45,  157,   51,   52,  147,  146,
       46,   49,   50,   49,   50,   51,   52,   51,   52,  102,
       53,  102,   47,   48,  145,   66,  102,   49,   51,   53,
      103,   53,   51,   67,   66,  103,   66,   50,   51,   66,
      103,  106,   67,  144,   67,   52,  106,   67,   76,   77,
       53,  143,  105,   67,   67,   53,  105,   76,   77,   76,
       77,  105,   76,   77,   84,   94,  142,  141,  132,   77,
       77,   97,   98,   84,   94,   84,   94,  131,   84,   94,
       97,   98,   97,   98,  107,   97,   98,  100,  107,  107,
      108,  130,   98,   98,  109,  108,  100,  108,  100,  109,

      111,  100,  110,  111,  112,  111,  129,  100,  100,  112,
      110,  115,  116,  128,  118,  110,  118,  127,  118,  134,
      115,  116,  115,  116,  134,  115,  116,  119,  121,  119,
      120,  119,  116,  116,  122,  124,  136,  121,  117,  121,
      136,  136,  121,  122,  124,  122,  124,  125,  122,  124,
       92,   91,   90,   89,  122,  122,  125,  133,  125,   88,
      135,  125,  133,  133,  135,  137,  138,  150,  139,  135,
      137,  138,  150,  139,  138,  137,  139,  140,  149,  148,
      151,  140,  149,  149,  148,  151,  140,  148,  151,  152,
      153,  154,  155,   87,  152,   82,  154,  155,  153,  163,

      154,  164,  165,  153,  163,  166,  164,  165,  166,  167,
      166,  168,  175,   72,  167,  167,  168,  175,  168,  176,
      177,  180,   68,   60,  176,  177,  180,  176,  184,  184,
      184,  184,  184,  184,  185,  185,  185,  185,  185,  185,
      186,  186,  186,  186,  186,  186,  187,  187,  187,  187,
      187,  187,  188,  188,  188,  188,  188,  188,  189,  189,
      189,  189,  189,  189,  191,  191,   59,  191,  192,  192,
      192,  192,  192,  193,  193,  193,  194,   34,  194,   26,
       25,   24,   23,   19,   10,    9,    6,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "spot.lex"
#line 2 "spot.lex"
#include <stdio.h>
#include "spot.tab.h"

static int com_cnt = 0;
int lineno = 1;
long sect1 = 0;
int svarflag = 0;
int unounflag = 0;
int umenuflag = 0;
int ufuncflag = 0;
int rtvarflag = 0;
int hmflag = 0;

extern char *lptr;
extern char ifile[];

void go();
char *copyToken(char *s1, char *s2);

#line 653 "lex.yy.c"

#define INITIAL 0
#define USER_CODE 1
#define CHAIN_DSCRPT 2
#define C_COMMENT 3
#define CPP_COMMENT 4
#define ESCAPE 5
#define INCLUDE 6
#define RUNNING_LINE 7
#define ACTION_ARG 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 25 "spot.lex"

#line 848 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 184 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 488 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

/* process the user code at the beginning of the spot file */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 28 "spot.lex"
{
		lineno++;
		sect1++;
	}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "spot.lex"
{					/* description of state variables structure */
		sect1 += yyleng;
		if(!svarflag) {
			svarflag = 1;
		}
	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "spot.lex"
{						/* description of user nouns structure */
		sect1 += yyleng;
		if (!unounflag) {
			unounflag = 1;
		}
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "spot.lex"
{						/* description of real time variables structure */
		sect1 += yyleng;
		if (!rtvarflag) {
			rtvarflag = 1;
		}
	}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "spot.lex"
{						/* description of user functions structure */
		sect1 += yyleng;
		if (!ufuncflag) {
			ufuncflag = 1;
		}
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 61 "spot.lex"
{						/* description of user menus structure */
		sect1 += yyleng;
		if (!umenuflag) {
			umenuflag = 1;
		}
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "spot.lex"
{					/* menu help menu */
		sect1 += yyleng;
		if (!hmflag) {
			hmflag = 1;
		}
	}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 75 "spot.lex"
sect1 += yyleng;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "spot.lex"
BEGIN(CHAIN_DSCRPT);		/* beginning of the state description */
	YY_BREAK


/* process the description of a chain */
case 10:
YY_RULE_SETUP
#line 82 "spot.lex"
return('{');							/* chain opening brace */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "spot.lex"
return('}');							/* chain closing brace */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "spot.lex"
{										/* begin argument to action */
		BEGIN(ACTION_ARG);
		return('(');
	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "spot.lex"
return(')');							/* end argument to action */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "spot.lex"
return(',');							/* comma separating arguments */
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "spot.lex"
return(':');								/* colon ending state name */
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "spot.lex"
return(PNUM);						/* process ID */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "spot.lex"
return(FIRST);						/* first state in a chain */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "spot.lex"
return(STATUS);					/* status of the chain */
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "spot.lex"
return(CODE);							/* an ecode to drop into E file */
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 95 "spot.lex"
return(TIME);							/* the time to wait in a state */
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "spot.lex"
return(RANDOM);					/* random amount to add to time */
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "spot.lex"
return(RESTART);					/* restart function */
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "spot.lex"
return(ACTION);							/* action */
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "spot.lex"
{										/* running line value */
		BEGIN(RUNNING_LINE);
		return(RUNL);
	}											/* abort list for a chain */
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "spot.lex"
return(ABORT);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 104 "spot.lex"
return(TO);								/* name of state to escape to */
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 105 "spot.lex"
return('&');							/* escape conditions */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 106 "spot.lex"
return('=');
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 107 "spot.lex"
return('<');
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 108 "spot.lex"
return('>');
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 109 "spot.lex"
return('?');
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 110 "spot.lex"
return('%');
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 111 "spot.lex"
{										/* list escape conditions */
		BEGIN(ESCAPE);
		return(ON);
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "spot.lex"
{		/* a string with all caps */
		++lptr;									/* and possibly digits */
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);
		return(CAPS);
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 122 "spot.lex"
{			/* an alphanumeric string with leading letter */
		++lptr;									/* and containing an array index */
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);
		return(STRING);
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 129 "spot.lex"
{						/*an address containing an array index */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr,yytext);
		return(ADDRESS);
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 136 "spot.lex"
{			/* a number */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);
		return(NUMBER);
	}
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 143 "spot.lex"
lineno++;								/* increment line number */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 144 "spot.lex"
{										/* begin a C style comment */
		com_cnt = 1;
		BEGIN(C_COMMENT);
	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 148 "spot.lex"
{										/* begin a C++ style comment */
		com_cnt = 1;
		BEGIN(CPP_COMMENT);
	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 152 "spot.lex"
{										/* a #include statement */
		fprintf(stdout,"#");
		BEGIN(INCLUDE);
	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 156 "spot.lex"
{}										/* eat character */
	YY_BREAK


/* process the arguments to an action */
case 43:
YY_RULE_SETUP
#line 161 "spot.lex"
{								/* closing parenthesis */
		BEGIN(CHAIN_DSCRPT);
		return(')');
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 165 "spot.lex"
return(',');					/* comma separating arguments */
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 166 "spot.lex"
{}								/* eat spaces */
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 167 "spot.lex"
lineno++;						/* increment line counter on new line */
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 168 "spot.lex"
{	/* argument is alphanumeric */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);
		return(STRING);
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 175 "spot.lex"
{	/* argument is an address */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr,yytext);
		return(STRING);
	}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 182 "spot.lex"
{ /* argument is a number */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);
		return(STRING);
	}
	YY_BREAK


/* process the arguments for an escape description */
case 50:
YY_RULE_SETUP
#line 193 "spot.lex"
{									/* escape if the bit is set */
		BEGIN(CHAIN_DSCRPT);
		return(PLUS);
	}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 197 "spot.lex"
{									/* escape if the bit is not set */
		BEGIN(CHAIN_DSCRPT);
		return(MINUS);
	}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 201 "spot.lex"
{								/* escape on time */
		BEGIN(CHAIN_DSCRPT);
		return(TIME);
	}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 205 "spot.lex"
{
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);

		BEGIN(CHAIN_DSCRPT);
		return(NUMBER);
	}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 214 "spot.lex"
{	/* name of flag variable */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);

		BEGIN(CHAIN_DSCRPT);
		return(CAPS);
	}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 223 "spot.lex"
{}
	YY_BREAK


/* process the arguments for a running line description */
case 56:
YY_RULE_SETUP
#line 228 "spot.lex"
{}									/* eat spaces */
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 229 "spot.lex"
{									/* raise running line by following value */
		BEGIN(CHAIN_DSCRPT);
		return(PLUS);
	}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 233 "spot.lex"
{									/* lower running line by following value */
		BEGIN(CHAIN_DSCRPT);
		return(MINUS);
	}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 237 "spot.lex"
{			/* a fixed running line value */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);

		BEGIN(CHAIN_DSCRPT);
		return(NUMBER);
	}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 246 "spot.lex"
{	/* a constant holding a running line value */
		++lptr;
		*lptr++ = ' ';
		yylval.cpval = lptr;
		lptr = copyToken(lptr, yytext);

		BEGIN(CHAIN_DSCRPT);
		return(CAPS);
	}
	YY_BREAK


/* process a C style comment */
case 61:
YY_RULE_SETUP
#line 259 "spot.lex"
com_cnt++;						/* check for nested C comments */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 260 "spot.lex"
{}								/* eat all characters in the comment */
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 261 "spot.lex"
lineno++;						/* increment line counter */
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 262 "spot.lex"
{								/* close C comment */
		if(--com_cnt == 0) {
			BEGIN(CHAIN_DSCRPT);
		}
	}
	YY_BREAK


/* process a C++ style comment */
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 271 "spot.lex"
{
		--com_cnt;
		lineno++;
		BEGIN(CHAIN_DSCRPT);
	}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 276 "spot.lex"
{}								/* eat all characters in the comment */
	YY_BREAK


/* process a #include statement */
case 67:
YY_RULE_SETUP
#line 281 "spot.lex"
fprintf(stdout,"%s ",yytext);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 282 "spot.lex"
{}							/* eat white space */
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 283 "spot.lex"
{
		lineno++;
		fprintf(stdout,"\n");

		BEGIN(CHAIN_DSCRPT);
	}
	YY_BREAK

case 70:
YY_RULE_SETUP
#line 290 "spot.lex"
ECHO;
	YY_BREAK
#line 1467 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(USER_CODE):
case YY_STATE_EOF(CHAIN_DSCRPT):
case YY_STATE_EOF(C_COMMENT):
case YY_STATE_EOF(CPP_COMMENT):
case YY_STATE_EOF(ESCAPE):
case YY_STATE_EOF(INCLUDE):
case YY_STATE_EOF(RUNNING_LINE):
case YY_STATE_EOF(ACTION_ARG):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 184 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 184 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 183);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 290 "spot.lex"



void go()
{
	BEGIN(USER_CODE);
}

char *copyToken(char *s1, char *s2)
{
	extern char buffer[MAXLEXBUF];
	extern char infile[50];

	if((s1 + strlen(s2)) > &buffer[MAXLEXBUF]) {
		fprintf(stderr, "Error in spot file %s, at line %d\n", infile, lineno);
		fprintf(stderr, "Total length of all tokens is too long.\n");
		fprintf(stderr, "Spot lexical analysis buffer will overflow.\n");
		fprintf(stderr, "You can reduce the length of tokens by\n");
		fprintf(stderr, "shortening the names and/or reducing the number\n");
		fprintf(stderr, "of those variables, actions, macros, and states\n");
		fprintf(stderr, "which are used after the \'%%%%\' symbol in the spot file\n\n");

		exit(-1);
	}

	while(*s1++ = *s2++);

	return(s1 - 1);
}

/* print out the user code at the beginning of the
 * spot file
 */
void printUserCode()
{
	long i;
	char tbuf;

	fseek(stdin, 0L, 0);

	for(i = 0; i < sect1; i++) {
		fread(&tbuf, 1, 1, stdin);
		fwrite(&tbuf, 1, 1, stdout);
	}
}

/*
 * Put the null structures into the accessory file if they have not been
 * initialized by the user.
 */
void printNullStructs()
{
	if(!svarflag) {
		fprintf(stdout, "VLIST state_vl[] = {\n");
		fprintf(stdout, "NS, };\n");
		fflush(stdout);
	}
	if(!unounflag) {
		fprintf(stdout, "NOUN unouns[] = {\n");
		fprintf(stdout, "\"\",\n");
		fprintf(stdout, "};\n");
	}
	if(!rtvarflag) {
		fprintf(stdout, "RTVAR rtvars[] = {\n");
		fprintf(stdout, "{\"\"},\n");
		fprintf(stdout, "};\n");
	}
	if(!ufuncflag) {
		fprintf(stdout, "USER_FUNC ufuncs[] = {\n");
		fprintf(stdout, "{\"\"},\n");
		fprintf(stdout, "};\n");
	}
	if(!umenuflag) {
		fprintf(stdout, "MENU umenus[] = {\n");
	  	if(!svarflag || !hmflag) {
            fprintf(stdout, "\"state_vars\",\t&state_vl, NP, NP, 0, NP, NS,\n");
        }
		else {
            fprintf(stdout, "\"state_vars\",\t&state_vl, NP, NP, 0, NP, hm_sv_vl,\n");
        }
		fprintf(stdout, "NS,\n");
		fprintf(stdout, "};\n");
	}
}

