#
# Sun/Vax makefile
#
# 23Apr88	LMO	remove argument passing for paths
#
# 
M = $(MFLAGS)

include ../MakefileWarn

include ../MakefileHdr
	(cd lib;     $(MAKE) $(M) $@)
	(cd fonts;   $(MAKE) $(M) $@)
	(cd inter ;  $(MAKE) $(M) $@ )
	(cd tools;   $(MAKE) $(M) $@ )
#	(cd tigtool; $(MAKE) $(M) $@ )
#	(cd hershtools;  $(MAKE) $(M) $@ )
