/* Variables header for application - AppBuilder 2.03  */

/* Internal Module Links */
const int ABI_eyeWinSumPictures = 0;
const int ABI_daSumPictures = 1;
const int ABI_memArraySumPictures = 2;
const int ABI_rampSumPictures = 3;
const int ABI_userMenuPictures = 4;
const int ABI_userFunctionPictures = 5;
const int ABI_userMenuWindow = 6;
const int ABI_stateDebugPictures = 7;
const int ABI_userRtVarsPictures = 8;
const int ABI_sigSumPictures = 9;
const int ABI_rexMessageDialog = 10;
const int ABI_scoreAlertDialog = 11;
const int ABI_stateDebugDialog = 12;
const int ABI_stateDebugWindow = 13;

/* 'base' Window link */
const int ABN_base = 0;
const int ABN_controlsMenuButton = 1;
const int ABN_statesMenuButton = 2;
const int ABN_userMenuButton = 3;
const int ABN_eyeWindowsMenuButton = 4;
const int ABN_analogSignalsMenuButton = 5;
const int ABN_saccadeDetectorMenuButton = 6;
const int ABN_bitsMenuButton = 7;
const int ABN_clockOnOffButton = 8;
const int ABN_pdigmOnOffButton = 9;
const int ABN_resetStatesToggle = 10;
const int ABN_windowsOnOffButton = 11;
const int ABN_debugOnOffButton = 12;
const int ABN_stateDebugTimer = 13;

/* 'signalDialog' Dialog link */
const int ABN_signalDialog = 14;
const int ABN_signalDialogLabel = 15;
const int ABN_signalList = 16;
const int ABN_asADchannel = 17;
const int ABN_asADdelay = 18;
const int ABN_asSigOffToggle = 19;
const int ABN_asADToggle = 20;
const int ABN_asMemoryToggle = 21;
const int ABN_asComputeToggle = 22;
const int ABN_asTitleTxt = 23;
const int ABN_adVariableGroup = 24;
const int ABN_asEyehToggle = 25;
const int ABN_asEyevToggle = 26;
const int ABN_asOeyehToggle = 27;
const int ABN_asOeyevToggle = 28;
const int ABN_asOtherhToggle = 29;
const int ABN_asOthervToggle = 30;
const int ABN_asAddhToggle = 31;
const int ABN_asAddvToggle = 32;
const int ABN_asJoyhToggle = 33;
const int ABN_asJoyvToggle = 34;
const int ABN_memorySourceGroup = 35;
const int ABN_asDA0Toggle = 36;
const int ABN_asDA1Toggle = 37;
const int ABN_asDA2Toggle = 38;
const int ABN_asDA3Toggle = 39;
const int ABN_asRamp0XToggle = 40;
const int ABN_asRamp0YToggle = 41;
const int ABN_asRamp1XToggle = 42;
const int ABN_asRamp1YToggle = 43;
const int ABN_asWD0XToggle = 44;
const int ABN_asWD0YToggle = 45;
const int ABN_asWD1XToggle = 46;
const int ABN_asWD1YToggle = 47;
const int ABN_computedSignalGroup = 48;
const int ABN_asVerghToggle = 49;
const int ABN_asVergvToggle = 50;
const int ABN_asCyclophToggle = 51;
const int ABN_asCyclopvToggle = 52;
const int ABN_asGazehToggle = 53;
const int ABN_asGazevToggle = 54;
const int ABN_asOgazehToggle = 55;
const int ABN_asOgazevToggle = 56;
const int ABN_asVgazehToggle = 57;
const int ABN_asVgazevToggle = 58;
const int ABN_asCgazehToggle = 59;
const int ABN_asCgazevToggle = 60;
const int ABN_asAquireGroup = 61;
const int ABN_asAquire2000Toggle = 62;
const int ABN_asAquire1000Toggle = 63;
const int ABN_asAquire500Toggle = 64;
const int ABN_asAquire250Toggle = 65;
const int ABN_asStoreGroup = 66;
const int ABN_asStore2000Toggle = 67;
const int ABN_asStore1000Toggle = 68;
const int ABN_asStore500Toggle = 69;
const int ABN_asStore250Toggle = 70;
const int ABN_asCalGroup = 71;
const int ABN_asCal204Toggle = 72;
const int ABN_asCal102Toggle = 73;
const int ABN_asCal51Toggle = 74;
const int ABN_asCal25Toggle = 75;
const int ABN_asCal12Toggle = 76;
const int ABN_asCal6Toggle = 77;
const int ABN_asCalNoiseToggle = 78;

/* 'sigSumDialog' Dialog link */
const int ABN_sigSumDialog = 79;
const int ABN_sigSumScrollArea = 80;

/* 'eyeWinSumDialog' Dialog link */
const int ABN_eyeWinSumDialog = 81;
const int ABN_eyeWinSumScrollArea = 82;

/* 'stateListDialog' Dialog link */
const int ABN_stateListDialog = 83;
const int ABN_stateListLabel = 84;
const int ABN_stateDialogTree = 85;
const int ABN_statePresetTime = 86;
const int ABN_stateRandomTime = 87;
const int ABN_stateRunLineVal = 88;
const int ABN_stateRunLineFlagGroup = 89;
const int ABN_stateRunLineAbsFlag = 90;
const int ABN_stateRunLineRelFlag = 91;
const int ABN_stateArg1FormatGroup = 92;
const int ABN_stateArg1DecToggle = 93;
const int ABN_stateArg1HexToggle = 94;
const int ABN_stateArg2FormatGroup = 95;
const int ABN_stateArg2DecToggle = 96;
const int ABN_stateArg2HexToggle = 97;
const int ABN_stateArg3FormatGroup = 98;
const int ABN_stateArg3DecToggle = 99;
const int ABN_stateArg3HexToggle = 100;
const int ABN_stateArg4FormatGroup = 101;
const int ABN_stateArg4DecToggle = 102;
const int ABN_stateArg4HexToggle = 103;
const int ABN_stateArg5FormatGroup = 104;
const int ABN_stateArg5DecToggle = 105;
const int ABN_stateArg5HexToggle = 106;
const int ABN_stateArg6FormatGroup = 107;
const int ABN_stateArg6DecToggle = 108;
const int ABN_stateArg6HexToggle = 109;
const int ABN_stateArg7FormatGroup = 110;
const int ABN_stateArg7DecToggle = 111;
const int ABN_stateArg7HexToggle = 112;
const int ABN_stateArg8FormatGroup = 113;
const int ABN_stateArg8DecToggle = 114;
const int ABN_stateArg8HexToggle = 115;
const int ABN_stateArg9FormatGroup = 116;
const int ABN_stateArg9DecToggle = 117;
const int ABN_stateArg9HexToggle = 118;
const int ABN_stateArg10FormatGroup = 119;
const int ABN_stateArg10DecToggle = 120;
const int ABN_stateArg10HexToggle = 121;
const int ABN_stateArg1Val = 122;
const int ABN_stateArg2Val = 123;
const int ABN_stateArg3Val = 124;
const int ABN_stateArg4Val = 125;
const int ABN_stateArg5Val = 126;
const int ABN_stateArg6Val = 127;
const int ABN_stateArg7Val = 128;
const int ABN_stateArg8Val = 129;
const int ABN_stateArg9Val = 130;
const int ABN_stateArg10Val = 131;
const int ABN_firstEscButton = 132;
const int ABN_secondEscButton = 133;
const int ABN_thirdEscButton = 134;
const int ABN_fourthEscButton = 135;
const int ABN_fifthEscButton = 136;
const int ABN_sixthEscButton = 137;
const int ABN_seventhEscButton = 138;
const int ABN_eighthEscButton = 139;
const int ABN_ninthEscButton = 140;
const int ABN_tenthEscButton = 141;

/* 'eyeWinDialog' Dialog link */
const int ABN_eyeWinDialog = 142;
const int ABN_eyeWinLabel = 143;
const int ABN_eyeWinList = 144;
const int ABN_eyeWinDialogButton = 145;
const int ABN_eyeWinXposGroup = 146;
const int ABN_eyeWinXposDPtoggle = 147;
const int ABN_eyeWinXposDAtoggle = 148;
const int ABN_eyeWinXposRXtoggle = 149;
const int ABN_eyeWinXposJXtoggle = 150;
const int ABN_eyeWinXposSigtoggle = 151;
const int ABN_eyeWinXposMemtoggle = 152;
const int ABN_eyeWinXposNumGroup = 153;
const int ABN_eyeWinXposSrcNumOvrRide = 154;
const int ABN_eyeWinXposSrcNum = 155;
const int ABN_eyeWinYposGroup = 156;
const int ABN_eyeWinYposDPtoggle = 157;
const int ABN_eyeWinYposDAtoggle = 158;
const int ABN_eyeWinYposRYtoggle = 159;
const int ABN_eyeWinYposJYtoggle = 160;
const int ABN_eyeWinYposSigtoggle = 161;
const int ABN_eyeWinYposMemtoggle = 162;
const int ABN_eyeWinYposNumGroup = 163;
const int ABN_eyeWinYposSrcNumOvrRide = 164;
const int ABN_eyeWinYposSrcNum = 165;
const int ABN_eyeWinXchkGroup = 166;
const int ABN_eyeWinXchkDPtoggle = 167;
const int ABN_eyeWinXchkDAtoggle = 168;
const int ABN_eyeWinXchkRXtoggle = 169;
const int ABN_eyeWinXchkJXtoggle = 170;
const int ABN_eyeWinXchkSigtoggle = 171;
const int ABN_eyeWinXchkMemtoggle = 172;
const int ABN_eyeWinXchkNumGroup = 173;
const int ABN_eyeWinXchkSrcNumOvrRide = 174;
const int ABN_eyeWinXchkSrcNum = 175;
const int ABN_eyeWinYchkGroup = 176;
const int ABN_eyeWinYchkDPtoggle = 177;
const int ABN_eyeWinYchkDAtoggle = 178;
const int ABN_eyeWinYchkRYtoggle = 179;
const int ABN_eyeWinYchkJYtoggle = 180;
const int ABN_eyeWinYchkSigtoggle = 181;
const int ABN_eyeWinYchkMemtoggle = 182;
const int ABN_eyeWinYchkNumGroup = 183;
const int ABN_eyeWinYchkSrcNumOvrRide = 184;
const int ABN_eyeWinYchkSrcNum = 185;
const int ABN_eyeWinPosGroup = 186;
const int ABN_eyeWinPosOvrRide = 187;
const int ABN_eyeWinXpos = 188;
const int ABN_eyeWinYpos = 189;
const int ABN_eyeWinSizGroup = 190;
const int ABN_eyeWinSizOvrRide = 191;
const int ABN_eyeWinWidth = 192;
const int ABN_eyeWinHeight = 193;
const int ABN_eyeWinXposAct = 194;
const int ABN_eyeWinYposAct = 195;
const int ABN_eyeWinWidthAct = 196;
const int ABN_eyeWinHeightAct = 197;
const int ABN_eyeWinXposNamAct = 198;
const int ABN_eyeWinXposSrcNumAct = 199;
const int ABN_eyeWinYposNamAct = 200;
const int ABN_eyeWinYposSrcNumAct = 201;
const int ABN_eyeWinXchkNamAct = 202;
const int ABN_eyeWinXchkSrcNumAct = 203;
const int ABN_eyeWinYchkNamAct = 204;
const int ABN_eyeWinYchkSrcNumAct = 205;
const int ABN_eyeWinWindowOnOffGroup = 206;
const int ABN_eyeWinOnToggle = 207;
const int ABN_eyeWinOffToggle = 208;
const int ABN_eyeWndChkRate = 209;

/* 'processDialog' Dialog link */
const int ABN_processDialog = 210;
const int ABN_processPreTime = 211;
const int ABN_processPostTime = 212;
const int ABN_processPreTimeOvrRide = 213;
const int ABN_processPostTimeOvrRide = 214;
const int ABN_processStateProcRate = 215;
const int ABN_processUnitControlGroup = 216;
const int ABN_processUnitSaveToggle = 217;
const int ABN_processUnitIgnoreToggle = 218;
const int ABN_processMexWexControlGroup = 219;
const int ABN_processMWOffToggle = 220;
const int ABN_processMWVer1Toggle = 221;
const int ABN_processMWVer2Toggle = 222;
const int ABN_processPlexonControlGroup = 223;
const int ABN_processPlexonSaveToggle = 224;
const int ABN_processPlexonIgnoreToggle = 225;
const int ABN_processSMIControlGroup = 226;
const int ABN_processSMIOnToggle = 227;
const int ABN_processSMIOffToggle = 228;
const int ABN_processADgainGroup = 229;
const int ABN_processADgain1Toggle = 230;
const int ABN_processADgain2Toggle = 231;
const int ABN_processADgain4Toggle = 232;
const int ABN_processADgain8Toggle = 233;
const int ABN_processADrateGroup = 234;
const int ABN_processADrate2000Toggle = 235;
const int ABN_processADrate1000Toggle = 236;
const int ABN_processDebugGroup = 237;
const int ABN_processDBrotateToggle = 238;
const int ABN_processDBinmemToggle = 239;
const int ABN_processDBfileToggle = 240;
const int ABN_processPreTimeAct = 241;
const int ABN_processPostTimeAct = 242;
const int ABN_clockWarnLabel = 243;
const int ABN_printDebugButton = 244;

/* 'rampDialog' Dialog link */
const int ABN_rampDialog = 245;
const int ABN_rampLabel = 246;
const int ABN_rampDialogButton = 247;
const int ABN_rampAnchorAct = 248;
const int ABN_rampLengthAct = 249;
const int ABN_rampAngleAct = 250;
const int ABN_rampVelocityAct = 251;
const int ABN_rampXoffAct = 252;
const int ABN_rampYoffAct = 253;
const int ABN_rampEcodeAct = 254;
const int ABN_rampPhiDeviceAct = 255;
const int ABN_rampPhiOnTimeAct = 256;
const int ABN_rampPhiOffTimeAct = 257;
const int ABN_rampAnchorGroup = 258;
const int ABN_rampCenPtToggle = 259;
const int ABN_rampBegPtToggle = 260;
const int ABN_rampEndPtToggle = 261;
const int ABN_ramp25msButton = 262;
const int ABN_rampAnchorOvrRide = 263;
const int ABN_rampLength = 264;
const int ABN_rampAngle = 265;
const int ABN_rampVelocity = 266;
const int ABN_rampXoff = 267;
const int ABN_rampYoff = 268;
const int ABN_rampEcode = 269;
const int ABN_rampPhiDevice = 270;
const int ABN_rampPhiOnTime = 271;
const int ABN_rampPhiOffTime = 272;
const int ABN_rampLengthOvrRide = 273;
const int ABN_rampAngleOvrRide = 274;
const int ABN_rampVelocityOvrRide = 275;
const int ABN_rampXoffOvrRide = 276;
const int ABN_rampYoffOvrRide = 277;
const int ABN_rampEcodeOvrRide = 278;
const int ABN_rampPhiDevOvrRide = 279;
const int ABN_rampPhiOnOvrRide = 280;
const int ABN_rampPhiOffOvrRide = 281;
const int ABN_rampList = 282;

/* 'sacDecDialog' Dialog link */
const int ABN_sacDecDialog = 283;
const int ABN_sacDecHrange = 284;
const int ABN_sacDecVrange = 285;
const int ABN_sacDecPeakVel = 286;
const int ABN_sacDecStartVel = 287;
const int ABN_sacDecEndVel = 288;
const int ABN_sacDecMaxVel = 289;
const int ABN_sacDecMinVel = 290;
const int ABN_sacDecMaxDur = 291;
const int ABN_sacDecMinDur = 292;
const int ABN_sacDecDelay = 293;
const int ABN_sacDecOnToggle = 294;
const int ABN_sacDecOffToggle = 295;

/* 'daConvDialog' Dialog link */
const int ABN_daConvDialog = 296;
const int ABN_daMenuOnOffButton = 297;
const int ABN_daDialogLabel = 298;
const int ABN_daSourceGroup = 299;
const int ABN_daStandbyToggle = 300;
const int ABN_daRampXToggle = 301;
const int ABN_daRampYToggle = 302;
const int ABN_daJoyXToggle = 303;
const int ABN_daJoyYToggle = 304;
const int ABN_daSignalToggle = 305;
const int ABN_daWinXToggle = 306;
const int ABN_daWinYToggle = 307;
const int ABN_daMemToggle = 308;
const int ABN_daModeGroup = 309;
const int ABN_daDirectToggle = 310;
const int ABN_daOffConToggle = 311;
const int ABN_daOffStbyToggle = 312;
const int ABN_daSourceNumOvrRide = 313;
const int ABN_daOutputOvrRide = 314;
const int ABN_daOffsetOvrRide = 315;
const int ABN_daSourceNum = 316;
const int ABN_daOutput = 317;
const int ABN_daOffset = 318;
const int ABN_daConvList = 319;
const int ABN_daSourceAct = 320;
const int ABN_daModeAct = 321;
const int ABN_daSourceNumAct = 322;
const int ABN_daOutputAct = 323;
const int ABN_daOffsetAct = 324;

/* 'daSumDialog' Dialog link */
const int ABN_daSumDialog = 325;
const int ABN_daSumScrollArea = 326;

/* 'memArrayDialog' Dialog link */
const int ABN_memArrayDialog = 327;
const int ABN_memArrayMenuButton = 328;
const int ABN_memArrayDialogLabel = 329;
const int ABN_memArrayCount = 330;
const int ABN_memArrayMsec = 331;
const int ABN_memArrayRepeat = 332;
const int ABN_memArrayAddress = 333;
const int ABN_maDialogAddrOvrRide = 334;
const int ABN_maDialogPtsOvrRide = 335;
const int ABN_maDialogMsecOvrRide = 336;
const int ABN_maDialogRepeatOvrRide = 337;
const int ABN_memArrayList = 338;
const int ABN_memArrayAddressAct = 339;
const int ABN_memArrayCountAct = 340;
const int ABN_memArrayMsecAct = 341;
const int ABN_memArrayRepeatAct = 342;

/* 'memArraySumDialog' Dialog link */
const int ABN_memArraySumDialog = 343;
const int ABN_memArrayScrollArea = 344;

/* 'eyeOffDialog' Dialog link */
const int ABN_eyeOffDialog = 345;
const int ABN_eyeOffDialogButton = 346;
const int ABN_eyeHOvrRide = 347;
const int ABN_eyeVOvrRide = 348;
const int ABN_oeyeHOvrRide = 349;
const int ABN_oeyeVOvrRide = 350;
const int ABN_eyeOffHorizOff = 351;
const int ABN_eyeOffVertOff = 352;
const int ABN_eyeOffOthHorizOff = 353;
const int ABN_eyeOffOthVertOff = 354;
const int ABN_eyeOffHorizOffAct = 355;
const int ABN_eyeOffVertOffAct = 356;
const int ABN_eyeOffOthHorizOffAct = 357;
const int ABN_eyeOffOthVertOffAct = 358;

/* 'bitsDialog' Dialog link */
const int ABN_bitsDialog = 359;
const int ABN_bitsLabel = 360;
const int ABN_bitsDeviceNumb = 361;
const int ABN_bitsStartPortNumber = 362;
const int ABN_bitsPort0Label = 363;
const int ABN_bitsPort1Label = 364;
const int ABN_bitsPort2Label = 365;
const int ABN_bitsP0Group = 366;
const int ABN_bitsP0B7Toggle = 367;
const int ABN_bitsP0B6Toggle = 368;
const int ABN_bitsP0B5Toggle = 369;
const int ABN_bitsP0B4Toggle = 370;
const int ABN_bitsP0B3Toggle = 371;
const int ABN_bitsP0B2Toggle = 372;
const int ABN_bitsP0B1Toggle = 373;
const int ABN_bitsP0B0Toggle = 374;
const int ABN_bitsP1Group = 375;
const int ABN_bitsP1B7Toggle = 376;
const int ABN_bitsP1B6Toggle = 377;
const int ABN_bitsP1B5Toggle = 378;
const int ABN_bitsP1B4Toggle = 379;
const int ABN_bitsP1B3Toggle = 380;
const int ABN_bitsP1B2Toggle = 381;
const int ABN_bitsP1B1Toggle = 382;
const int ABN_bitsP1B0Toggle = 383;
const int ABN_bitsP2Group = 384;
const int ABN_bitsP2B7Toggle = 385;
const int ABN_bitsP2B6Toggle = 386;
const int ABN_bitsP2B5Toggle = 387;
const int ABN_bitsP2B4Toggle = 388;
const int ABN_bitsP2B3Toggle = 389;
const int ABN_bitsP2B2Toggle = 390;
const int ABN_bitsP2B1Toggle = 391;
const int ABN_bitsP2B0Toggle = 392;
const int ABN_bitsPort0ControlGroup = 393;
const int ABN_bitsPort0ToggleToggle = 394;
const int ABN_bitsPort0PulseToggle = 395;
const int ABN_bitsPort0SetToggle = 396;
const int ABN_bitsPort0ResetToggle = 397;
const int ABN_bitsPort1ControlGroup = 398;
const int ABN_bitsPort1ToggleToggle = 399;
const int ABN_bitsPort1PulseToggle = 400;
const int ABN_bitsPort1SetToggle = 401;
const int ABN_bitsPort1ResetToggle = 402;
const int ABN_bitsPort2ControlGroup = 403;
const int ABN_bitsPort2ToggleToggle = 404;
const int ABN_bitsPort2PulseToggle = 405;
const int ABN_bitsPort2SetToggle = 406;
const int ABN_bitsPort2ResetToggle = 407;
const int ABN_bitsPort4Label = 408;
const int ABN_bitsPort5Label = 409;
const int ABN_bitsPort6Label = 410;
const int ABN_bitsP4Group = 411;
const int ABN_bitsP4B7Toggle = 412;
const int ABN_bitsP4B6Toggle = 413;
const int ABN_bitsP4B5Toggle = 414;
const int ABN_bitsP4B4Toggle = 415;
const int ABN_bitsP4B3Toggle = 416;
const int ABN_bitsP4B2Toggle = 417;
const int ABN_bitsP4B1Toggle = 418;
const int ABN_bitsP4B0Toggle = 419;
const int ABN_bitsP5Group = 420;
const int ABN_bitsP5B7Toggle = 421;
const int ABN_bitsP5B6Toggle = 422;
const int ABN_bitsP5B5Toggle = 423;
const int ABN_bitsP5B4Toggle = 424;
const int ABN_bitsP5B3Toggle = 425;
const int ABN_bitsP5B2Toggle = 426;
const int ABN_bitsP5B1Toggle = 427;
const int ABN_bitsP5B0Toggle = 428;
const int ABN_bitsP6Group = 429;
const int ABN_bitsP6B7Toggle = 430;
const int ABN_bitsP6B6Toggle = 431;
const int ABN_bitsP6B5Toggle = 432;
const int ABN_bitsP6B4Toggle = 433;
const int ABN_bitsP6B3Toggle = 434;
const int ABN_bitsP6B2Toggle = 435;
const int ABN_bitsP6B1Toggle = 436;
const int ABN_bitsP6B0Toggle = 437;
const int ABN_bitsPort4ControlGroup = 438;
const int ABN_bitsPort4ToggleToggle = 439;
const int ABN_bitsPort4PulseToggle = 440;
const int ABN_bitsPort4SetToggle = 441;
const int ABN_bitsPort4ResetToggle = 442;
const int ABN_bitsPort5ControlGroup = 443;
const int ABN_bitsPort5ToggleToggle = 444;
const int ABN_bitsPort5PulseToggle = 445;
const int ABN_bitsPort5SetToggle = 446;
const int ABN_bitsPort5ResetToggle = 447;
const int ABN_bitsPort6ControlGroup = 448;
const int ABN_bitsPort6ToggleToggle = 449;
const int ABN_bitsPort6PulseToggle = 450;
const int ABN_bitsPort6SetToggle = 451;
const int ABN_bitsPort6ResetToggle = 452;

/* 'sigSumPictures' Picture link */
const int ABN_sigSumPictures = 453;
const int ABN_sigSumLabel = 454;
const int ABN_sigSumTypeText = 455;
const int ABN_sigSumChannelInt = 456;
const int ABN_sigSumArateInt = 457;
const int ABN_sigSumSrateInt = 458;
const int ABN_sigSumCalInt = 459;
const int ABN_sigSumGainInt = 460;
const int ABN_sigSumDelayInt = 461;
const int ABN_sigSumNameText = 462;
const int ABN_sigSumTitleText = 463;

/* 'eyeWinSumPictures' Picture link */
const int ABN_eyeWinSumPictures = 464;
const int ABN_eyeWinSumLabel = 465;
const int ABN_eyeWinSumXpos = 466;
const int ABN_eyeWinSumYpos = 467;
const int ABN_eyeWinSumWidth = 468;
const int ABN_eyeWinSumHeight = 469;
const int ABN_eyeWinSumXposNam = 470;
const int ABN_eyeWinSumXposNum = 471;
const int ABN_eyeWinSumYposNam = 472;
const int ABN_eyeWinSumYposNum = 473;
const int ABN_eyeWinSumXchkNam = 474;
const int ABN_eyeWinSumXchkNum = 475;
const int ABN_eyeWinSumYchkNam = 476;
const int ABN_eyeWinSumYchkNum = 477;

/* 'daSumPictures' Picture link */
const int ABN_daSumPictures = 478;
const int ABN_daSumDAlabel = 479;
const int ABN_daSumDAname = 480;
const int ABN_daSumDAnumber = 481;
const int ABN_daSumDAmode = 482;
const int ABN_daSumDAoffset = 483;

/* 'memArraySumPictures' Picture link */
const int ABN_memArraySumPictures = 484;
const int ABN_memArraySumLabel = 485;
const int ABN_memArraySumSize = 486;
const int ABN_memArraySumRate = 487;
const int ABN_memArraySumRepeat = 488;
const int ABN_memArraySumAddress = 489;

/* 'rampSumDialog' Dialog link */
const int ABN_rampSumDialog = 490;
const int ABN_rampSumScrollArea = 491;

/* 'rampSumPictures' Picture link */
const int ABN_rampSumPictures = 492;
const int ABN_rampSumLabel = 493;
const int ABN_rampSumAnchorText = 494;
const int ABN_rampSumLength = 495;
const int ABN_rampSumAngle = 496;
const int ABN_rampSumVelocity = 497;
const int ABN_rampSumXoff = 498;
const int ABN_rampSumYoff = 499;
const int ABN_rampSumEcode = 500;
const int ABN_rampSumPhi = 501;
const int ABN_rampSumPhiOn = 502;
const int ABN_rampSumPhiOff = 503;

/* 'userMenuPictures' Picture link */
const int ABN_userMenuPictures = 504;
const int ABN_userMenuItemLabel = 505;
const int ABN_userMenuTextValue = 506;

/* 'userFunctionDialog' Dialog link */
const int ABN_userFunctionDialog = 507;
const int ABN_userFunctionScrollArea = 508;

/* 'userFunctionPictures' Picture link */
const int ABN_userFunctionPictures = 509;
const int ABN_userFunctionLabel = 510;
const int ABN_userFunctionLeftParen = 511;
const int ABN_userFunctionArgumentText = 512;
const int ABN_userFunctionRightParen = 513;

/* 'userMenuWindow' Window link */
const int ABN_userMenuWindow = 514;
const int ABN_scrollAreaGroup = 515;
const int ABN_userMenuScrollArea = 516;
const int ABN_userMenuArrayLabel = 517;
const int ABN_userMenuArrayIndex = 518;
const int ABN_argGroupText = 519;

/* 'smiDialog' Dialog link */
const int ABN_smiDialog = 520;
const int ABN_smiOffset = 521;
const int ABN_smiGain = 522;
const int ABN_smiOverrun = 523;
const int ABN_smiDebtog = 524;
const int ABN_smiDebtog2 = 525;
const int ABN_smiDeblval = 526;
const int ABN_smiDebhval = 527;
const int ABN_smiV0 = 528;
const int ABN_smiV1 = 529;
const int ABN_smiV2 = 530;
const int ABN_smiV3 = 531;
const int ABN_smiV4 = 532;
const int ABN_smiV5 = 533;
const int ABN_smiV6 = 534;
const int ABN_smiV7 = 535;
const int ABN_smiV8 = 536;
const int ABN_smiV9 = 537;
const int ABN_smiLater = 538;

/* 'stateDebugPictures' Picture link */
const int ABN_stateDebugPictures = 539;
const int ABN_stateButton = 540;

/* 'userRtVarsDialog' Dialog link */
const int ABN_userRtVarsDialog = 541;
const int ABN_userRtVarsMin = 542;
const int ABN_userRtVarsSec = 543;
const int ABN_userRtVarsReset = 544;
const int ABN_userRtVarsTimer = 545;
const int ABN_userRtVarsScrollArea = 546;

/* 'userRtVarsPictures' Picture link */
const int ABN_userRtVarsPictures = 547;
const int ABN_userRtVarLabel = 548;
const int ABN_userRtVarsInt = 549;
const int ABN_userRtVarsFloat = 550;

/* 'stateDebugDialog' Dialog link */
const int ABN_stateDebugDialog = 551;
const int ABN_stateTime = 552;
const int ABN_stateRandom = 553;
const int ABN_runningLine = 554;
const int ABN_stateRunLineToggleGroup = 555;
const int ABN_stateRunLineAbsToggle = 556;
const int ABN_stateRunLineRelToggle = 557;
const int ABN_stateArg1ToggleGroup = 558;
const int ABN_stateArg1DecFormat = 559;
const int ABN_stateArg1HexFormat = 560;
const int ABN_stateArg2ToggleGroup = 561;
const int ABN_stateArg2DecFormat = 562;
const int ABN_stateArg2HexFormat = 563;
const int ABN_stateArg3ToggleGroup = 564;
const int ABN_stateArg3DecFormat = 565;
const int ABN_stateArg3HexFormat = 566;
const int ABN_stateArg4ToggleGroup = 567;
const int ABN_stateArg4DecFormat = 568;
const int ABN_stateArg4HexFormat = 569;
const int ABN_stateArg5ToggleGroup = 570;
const int ABN_stateArg5DecFormat = 571;
const int ABN_stateArg5HexFormat = 572;
const int ABN_stateArg6ToggleGroup = 573;
const int ABN_stateArg6DecFormat = 574;
const int ABN_stateArg6HexFormat = 575;
const int ABN_stateArg7ToggleGroup = 576;
const int ABN_stateArg7DecFormat = 577;
const int ABN_stateArg7HexFormat = 578;
const int ABN_stateArg8ToggleGroup = 579;
const int ABN_stateArg8DecFormat = 580;
const int ABN_stateArg8HexFormat = 581;
const int ABN_stateArg9ToggleGroup = 582;
const int ABN_stateArg9DecFormat = 583;
const int ABN_stateArg9HexFormat = 584;
const int ABN_stateArg10ToggleGroup = 585;
const int ABN_stateArg10DecFormat = 586;
const int ABN_stateArg10HexFormat = 587;
const int ABN_stateArg1 = 588;
const int ABN_stateArg2 = 589;
const int ABN_stateArg3 = 590;
const int ABN_stateArg4 = 591;
const int ABN_stateArg5 = 592;
const int ABN_stateArg6 = 593;
const int ABN_stateArg7 = 594;
const int ABN_stateArg8 = 595;
const int ABN_stateArg9 = 596;
const int ABN_stateArg10 = 597;
const int ABN_stateEsc1Button = 598;
const int ABN_stateEsc2Button = 599;
const int ABN_stateEsc3Button = 600;
const int ABN_stateEsc4Button = 601;
const int ABN_stateEsc5Button = 602;
const int ABN_stateEsc6Button = 603;
const int ABN_stateEsc7Button = 604;
const int ABN_stateEsc8Button = 605;
const int ABN_stateEsc9Button = 606;
const int ABN_stateEsc10Button = 607;

/* 'stateDebugWindow' Dialog link */
const int ABN_stateDebugWindow = 608;
const int ABN_debugScrollContainer = 609;

/* 'rexMessageDialog' Dialog link */
const int ABN_rexMessageDialog = 610;
const int ABN_rexMessageText = 611;

/* 'scoreAlertDialog' Dialog link */
const int ABN_scoreAlertDialog = 612;
const int ABN_scoreAlertCancelButton = 613;
const int ABN_scoreAlertMultiText = 614;
const int ABN_scoreAlertTimer = 615;

/* 'statesMenu' Menu link */
const int ABN_statesMenu = 616;
const int ABN_statesAll = 617;
const int ABN_statesTime = 618;

/* 'controlsMenu' Menu link */
const int ABN_controlsMenu = 619;
const int ABN_controlsProcess = 620;
const int ABN_controlsRamps = 621;
const int ABN_controlsRampSum = 622;
const int ABN_controlsDA = 623;
const int ABN_controlsDAsum = 624;
const int ABN_controlsMemArray = 625;
const int ABN_controlsMemArraySum = 626;
const int ABN_smiControls = 627;

/* 'signalsMenu' Menu link */
const int ABN_signalsMenu = 628;
const int ABN_signalsMenuControls = 629;
const int ABN_signalsMenuSummary = 630;

/* 'eyeWindowMenu' Menu link */
const int ABN_eyeWindowMenu = 631;
const int ABN_eyeWinMenuControls = 632;
const int ABN_eyeWinMenuOffsets = 633;
const int ABN_eyeWinMenuSummary = 634;

/* 'userMenu' Menu link */
const int ABN_userMenu = 635;
const int ABN_userMenuItem = 636;
const int ABN_userFunctionItem = 638;
const int ABN_userMenuRtVars = 639;

